= Public Connectors SDK Resources

The link:https://github.com/lucidworks/connectors-sdk-resources[connectors SDK public Github repository] provides resources to help developers build their own
link:https://lucidworks.com/products/fusion-server/[Fusion] SDK Connectors.
Some of the resources include documentation and getting started guides, as well as example Connectors.

For developing a Java SDK based Connector, check out the link:./java-sdk/README.html[README].

Information on the current set of **example Java plugins** can be found link:./java-sdk/connectors/README.html[here].

== Fusion 4 Connectors Overview

The Connectors architecture in Fusion 4 and later is designed to be scalable. Depending on the Connector, jobs can be scaled by adding instances of just the Connector.
The fetching process for these types also supports distributed fetching, so that many instances can contribute to the same job.

Connectors can be hosted within Fusion, or can run remotely. In the hosted case, these Connectors are cluster aware.
This means that when a new instance of Fusion starts up, the Connectors on other Fusion nodes become aware of the new Connectors, and vice versa.
This simplifies scaling Connectors jobs.

In the remote case, Connectors become clients of Fusion. These clients run a lightweight process and communicate to Fusion using an efficient messaging format.
This option makes it possible to put the Connector wherever the data lives. In some cases, this might be required for performance or security and access reasons.

The communication of messages between Fusion and a remote Connector or hosted Connector are identical; Fusion sees them as the same kind of Connector.
This means you can implement a Connector locally, connect to a remote Fusion for initial testing, and when done, upload the exact same artifact (a zip file) into Fusion, so Fusion can host it for you.
The ability to run the Connector remotely makes the development process much quicker.

== Java SDK

The Java SDK brings a new set of components for making it simple to build a Connector in Java. Whether the plugin is a true crawler, or a simple iterative fetcher, the SDK supports both.

The link:./java-sdk/README.html[Java SDK] includes a set of base classes and interfaces. It also provides the Gradle build utilities for packaging up a Connector, and a Connector client application that can run your Connector remotely.

Many of the base features needed for a Connector are provided by Fusion itself.
When a Connector first connects to Fusion, it sends along its name, type, schema, and other metadata.
This connection then stays open, and the two systems can communicate bi-directionally as needed.

This makes it possible for Fusion to manage configuration data, the job state, scheduling, and encryption for example. The Fusion Admin UI also takes care of the view/presentation, by making use of the Connector's schema.

This client-based approach decouples Connectors from Fusion, which allows hot deployment of connectors through a simple connect call.

== Security
Fusion Connectors support SSL/TLS. See the link:security.html[security README] for setup.

=== gRPC
The underlying client/server technology used by these Connectors is a fast and efficient framework from Google called link:https://grpc.io/[gRPC].
The gRPC framework provides flexibility in the way services and their methods are defined. Other benefits of this framework include:

* HTTP/2 based transport
* Provides an efficient serialization format for data handling (protocol buffers)
* Allows bi-directional/multiplexed streams
* Flow control, also known as back pressure

== Distributed Data Store
The data persisted by the Connectors framework is distributed across the Fusion cluster. Each node holds its primary partition of the data, as well as backups of other partitions.
If a node goes down during a crawl, the data store remains intact and usable. Connector implementations do not need to be concerned with this layer, because it is all handled by Fusion.


Copyright 2018 link:https://lucidworks.com[Lucidworks]
