== Connector Java SDK Configuration

To build a valid connector configuration, you must:

* Define an interface.
* Extend `ConnectorConfig`.
* Apply a few annotations.
* Define connector "getter" methods and annotations.

All methods that are annotated with `@Property` and are considered to be configuration properties.
For example, `@Property() String name();` results in a String property called `name`.
This property would then be present in the generated schema.

Here is an example of the most basic configuration, along with required annotations and a sample property access methods:

```java
@RootSchema(
    name = "com.my.connector",
    title = "My Connector",
    description = "My Connector description",
    category = "My Category"
)
public interface MyConfig extends ConnectorConfig<MyConfig.Properties> {

  @Property(
      title = "Properties",
      required = true
  )
  public Properties properties();

  /**
   * Connector specific settings
   */
  interface Properties extends FetcherProperties {

    @Property(
        title = "My custom property",
        description = "My custom property description"
    )
    public Integer myCustomProperty();

  }

}

```

The metadata defined by `@RootSchema` is used by Fusion when showing the list of available connectors.
The `ConnectorConfig` base interface represents common, top-level settings required by all connectors.
The `type` parameter of the `ConnectorConfig` class indicates the interface to use for custom properties.

Once a connector configuration has been defined, it can be associated with the `ConnectorPlugin` class.
From that point, the framework takes care of providing the configuration instances to your connector.
It also generates the schema, and sends it along to Fusion when it connects to Fusion.

