== Random Connector

=== Connector Description

This connector generates a configurable number of documents, all with random titles and body fields.

=== Quick start

1. Clone the repo:
```
git clone https://github.com/lucidworks/connectors-sdk-resources.git
cd connectors-sdk-resources/java-sdk/connectors/
./gradlew assemblePlugins
```

2. This produces one zip file, named `random-connector.zip`, located in the `build/plugins` directory.
This artifact is now ready to be uploaded directly to Fusion as a connector plugin.

3. See the following [instructions](../README.md) on how to build, deploy, and run the plugi

=== Connector properties

==== Random content generator properties

[width="80%",cols="2, 6",options="header"]
|=========================================================
|Property Name |Property description
|Total |The total number of documents to generate
|Minimum number of sentences |The minimum number of sentences to generate per document, the random generator will use this value as lower bound to calculate a random number of sentences
| maximum number of sentences | The maximum number of sentences to generate per document, the random generator will use this value as upper bound to calculate a random number of sentences
|=========================================================

=== How to use the connector

- Create a configuration with the properties listed above.
- After the first job is completed, the connector will index the same number of documents as defined in the `Randon content generator properties.Total` property.