== Random Content Connector

This connector generates a configurable number of documents, all with random titles and body fields.

## Quick start

NOTE: This quick start assumes that Fusion is installed on the `/opt` path and its version is `4.0.1`

1. Clone the repo:
```
git clone https://github.com/lucidworks/connectors-sdk-resources.git
cd connectors-sdk-resources/java-sdk/connectors/
./gradlew assemblePlugins -PfusionHome=/opt/fusion/4.0.1 -PfusionVersion=4.0.1
```

2. This produces one zip file, named `random-connector-{version}.zip`, located in the `build/plugins` directory.
This artifact is now ready to be uploaded directly to Fusion as a connector plugin.

## Building

**Important**

You have to use gradle wrapper attached to the project. It runs custom gradle distribution.

### Random Content Plugin

Build the plugin zip:

```bash
../gradlew clean build :assemblePlugin
```

This produces one zip file, named `random-connector.zip`, located in the `build/libs` directory.

At this point, the generated zip could be uploaded directly to Fusion, but follow the steps below to run as a remote plugin.


## Start

Connect to Fusion plugin by using the client jar plus the plugin zip:

```bash
java  -jar ${fusionHome}/apps/connectors/connectors-rpc/client/connector-plugin-client-${fusionVersion}-uberjar.jar build/plugins/random-content-connector-{version}.zip
```

Start with debugging enabled:

```bash
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5010 -jar ${fusionHome}/apps/connectors/connectors-rpc/client/connector-plugin-client-${fusionVersion}-uberjar.jar build/plugins/random-content-connector-{version}.zip
```

Alternatively, when proper configuration is done in the `gradle.properties` file (fusionHome, fusionVersion and fusionRpcTarget properties), the plugin can also be run using a simple gradle task:

```bash
./gradlew connect
```

After running this, logging should show that it either was able to connect to Fusion, or not. If not, be sure you're using the right Fusion address/port. If not, the client jar can accept various related settings.

## Fusion
After the client process successfully connects to Fusion, you should see the Random Content Connector available in Fusion as a new connector type.
